name: CI

on:
  # try to run on all branches
  push:
    # branches: [ main, master, feature/ci-cd-setup ]
  pull_request:
    # branches: [ main, master, feature/ci-cd-setup ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # JavaScript/Node.js setup
      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.0
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      # python setup
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11" # or your preferred version
      - run: pip install flake8 black isort

      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm format:check
